import os
import subprocess
import glob
from pathlib import Path


def generate_motion_video(image_path: str, output_path: str):
    """
    CPU-compatible LivePortrait motion generator.
    Works on Windows + Linux + Colab.
    """

    ROOT = Path(__file__).resolve().parent.parent  # backend/
    LIVEPORTRAIT_DIR = ROOT / "LivePortrait"
    ANIM_DIR = LIVEPORTRAIT_DIR / "animations"
    DRIVING = LIVEPORTRAIT_DIR / "assets/examples/driving/d0.mp4"

    image_path = str(Path(image_path).resolve())
    output_path = str(Path(output_path).resolve())

    print("🎥 Running LivePortrait...")
    print("➡ CPU Mode (auto-detected by onnxruntime)")

    # clean old files
    ANIM_DIR.mkdir(parents=True, exist_ok=True)
    for f in glob.glob(str(ANIM_DIR / "*.mp4")):
        try: os.remove(f)
        except: pass

    # ------------------------------
    # LivePortrait inference command
    # ------------------------------
    cmd = [
        "python",
        str(LIVEPORTRAIT_DIR / "inference.py"),
        "-s", image_path,
        "-d", str(DRIVING),
        "--flag_crop_driving_video"
        # NO device flag → CPU auto fallback
    ]

    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    for line in process.stdout:
        print("🔧", line.strip())

    process.wait()

    # ------------------------------
    # Find latest resulting animation
    # ------------------------------
    mp4_files = sorted(
        glob.glob(str(ANIM_DIR / "*.mp4")),
        key=os.path.getmtime
    )

    if not mp4_files:
        raise RuntimeError("❌ No output generated by LivePortrait!")

    latest = Path(mp4_files[-1])

    # Move output to desired location
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    os.replace(latest, output_path)

    print("🎉 Final Motion Video Saved:", output_path)
    return output_path
